#!/bin/sh

cd ~
mkdir -p /etc/nginx/conf

download_n76i_nginx_config(){
wget --no-check-certificate -q "https://echbay.com/server/conf/index.php?file=$1&download=1&rand=1" -O /etc/nginx/conf/$1.conf
chmod 755 /etc/nginx/conf/$1.conf
}
#download_n76i_nginx_config "ddos1"
#download_n76i_nginx_config "ddos2"
#download_n76i_nginx_config "ssl"
download_n76i_nginx_config "all"
download_n76i_nginx_config "block"
download_n76i_nginx_config "staticfiles"
download_n76i_nginx_config "drop"

#
wget --no-check-certificate -q "https://echbay.com/server/conf/index.php?file=ssl_ciphers_vpssim&download=1&rand=1" -O /etc/nginx/ssl_ciphers_vpssim.conf
chmod 755 /etc/nginx/ssl_ciphers_vpssim.conf

#
chown root:root /etc/nginx/conf
chown root:root /etc/nginx/conf/*
chmod 755 /etc/nginx/conf/*


#
download_n76i_custom_nginx_config(){
wget --no-check-certificate -q "https://raw.githubusercontent.com/n76i/n76i-v/master/directadmin/data/templates/custom/$1.conf" -O $1.conf ; chmod 755 $1.conf
}

cd ~
mkdir -p /usr/local/directadmin/data/templates/custom

#
cd /usr/local/directadmin/data/templates/custom
download_n76i_custom_nginx_config "nginx_server"
download_n76i_custom_nginx_config "nginx_server_secure"
download_n76i_custom_nginx_config "nginx_server_secure_sub"
download_n76i_custom_nginx_config "nginx_server_sub"


# file custom cho tất cả domain
download_n76i_custom_n_config(){
wget --no-check-certificate -q "https://raw.githubusercontent.com/n76i/n76i-v/master/directadmin/data/templates/custom/nginx_server.conf.CUSTOM.3.txt" -O $1.conf.CUSTOM.3.pre ; chmod 755 $1.conf.CUSTOM.3.pre
}
download_n76i_custom_n_config "nginx_server"
download_n76i_custom_n_config "nginx_server_secure"
download_n76i_custom_n_config "nginx_server_secure_sub"
download_n76i_custom_n_config "nginx_server_sub"

#
cd ~

#
chown diradmin:diradmin /usr/local/directadmin/data/templates/custom
chown diradmin:diradmin /usr/local/directadmin/data/templates/custom/*
chmod 755 /usr/local/directadmin/data/templates/custom/*

#
cd /usr/local/directadmin/custombuild
./build rewrite_confs

cd ~
service nginx restart
