#!/bin/sh


cd ~
if [ -d /opt/n76i_vpssim ]; then
rm -rf /opt/n76i_vpssim/*
rm -rf /opt/n76i_vpssim
#sleep 5
fi

#
echo "Install unzip..."
sudo yum -y install unzip


# ưu tiên download file zip cho nó nhanh
cd /tmp
wget --no-check-certificate https://github.com/n76i/n76i-v/archive/refs/heads/master.zip -O n76i-v.zip
unzip -q n76i-v.zip
cd ~
if [ -d /tmp/n76i-v-master ]; then
    mkdir -p /opt/n76i_vpssim ; chmod 755 /opt/n76i_vpssim
    yes | cp -rf /tmp/n76i-v-master/. /opt/n76i_vpssim/
    rm -rf /tmp/n76i-v*
else
    echo "Install git..."
    sudo yum -y install git

    # update code
    if [ -d /opt/n76i_vpssim ]; then
        cd ~ ; cd /opt/n76i_vpssim && git pull ; cd ~
        #git commit -m "N76I-VPSSIM commit"
        #git pull origin master
        #git pull origin
        #git merge origin master
        # or clone new
    else
        git clone https://github.com/n76i/n76i-v /opt/n76i_vpssim
    fi
fi

#
cd ~

#sleep 5

find /opt/n76i_vpssim/script/vpssim/menu -type f -exec chmod 755 {} \;
/opt/n76i_vpssim/script/vpssim/menu/git-clone-done

#
echo "update N76I-VPSSIM menu"
mkdir -p /etc/vpssim/menu ; chmod 755 /etc/vpssim/menu
rm -rf /etc/vpssim/menu/*
yes | cp -rf /opt/n76i_vpssim/script/vpssim/menu/. /etc/vpssim/menu/

echo "Chmod 755 Menu"
/opt/n76i_vpssim/script/vpssim/menu/chmod-755-menu

#
echo "update N76I-VPSSIM conf"
mkdir -p /etc/nginx/conf ; chmod 755 /etc/nginx/conf
yes | cp -rf /opt/n76i_vpssim/script/vpssim/conf/. /etc/nginx/conf/
find /etc/nginx/conf -type f -exec chmod 644 {} \;
