#!/bin/bash
. /home/vpssim.conf
. /opt/n76i_vpssim/script/vpssim/nginx-setup.conf

# check current open ssl version
echo $(openssl version) > /tmp/current_openssl_version
cat /tmp/current_openssl_version
echo $opensslversion
check_openssl_version=$(grep $openssl_version /tmp/current_openssl_version)
echo $check_openssl_version

# update if version not lasted
if [ "$check_openssl_version" = "" ]; then
/opt/n76i_vpssim/script/vpssim/menu/nang-cap-openssl-auto
else
echo "OpenSSL lasted version..."
fi
